media:
  - name: images
    label: Bilder
    input: src/content/images
content:
  - name: articles
    label: Artiklar
    type: collection
    path: src/content/articles
    filename: "{primary}.md"
    fields:
      - { name: title, label: Titel, type: string, required: true }
      - { name: order, label: Rang, type: number, required: true }
      - { name: image, label: Bild, type: image }
      - { name: body, label: Innehåll, type: rich-text }
  - name: lodges
    label: Loger
    type: collection
    path: src/content/lodges
    filename: "{primary}.md"
    fields:
      - { name: name, label: Namn, type: string, required: true }
      - { name: number, label: Nummer, type: number, required: true }
      - { name: city, label: Ort, type: string, required: true }
      - { name: streetAddress, label: Gatuadress, type: string, required: true }
      - { name: email, label: E-post, type: string, required: true }
      - {
          name: seal,
          label: Sigill,
          type: image,
          required: true,
          media: images,
        }
      - { name: meetingInfo, label: Mötesinfo, type: text }
      - name: schedule
        label: Arbetsordning
        type: object
        fields:
          - { name: date, label: Datum, type: date, format: "yyyy-MM-dd" }
          - { work: extra, label: Arbete, type: string }
        list: true
        required: true
      - { name: body, label: Beskrivning, type: rich-text, required: true }
