components:
  articleRef:
    type: reference
    options: { collection: 'articles' }
  plainLink:
    type: object
    fields:
      - { name: url, label: URL, type: string }
      - { name: title, label: Titel, type: string }
  menuLink:
    type: block
    blockKey: type
    blocks:
      - name: plainLink
        component: plainLink
      - name: article
        component: articleRef
content:
  - name: menu
    type: file
    path: src/content/meny.json
    format: json
    fields:
      - name: main
        component: menuLink
  - name: articles
    type: collection
    path: src/content/articles
    filename: "{primary}.md"
    fields:
      - { name: title, label: Titel, type: string, required: true }
      - { name: image, label: Bild, type: image }
      - { name: body, label: Innehåll, type: rich-text }
