media:
  - name: images
    label: Bilder
    input: src/images
    output: /fnam/images
content:
  - name: articles
    label: Artiklar
    type: collection
    path: src/content/articles
    filename: "{primary}.md"
    fields:
      - { name: title, label: Titel, type: string, required: true }
      - { name: order, label: Rang, type: number, required: true }
      - { name: image, label: Bild, type: image }
      - { name: body, label: Innehåll, type: rich-text }
