media:
  - name: images
    label: Bilder
    input: src/content/images
    output: $images
components:
  articleLink:
    label: Länk
    type: reference
    options: {collection: 'articles', label: "{title}"}
  menuLink:
    type: object
    fields:
      - { name: url, label: URL, type: string, required: true }
      - { name: title, label: Titel, type: string, required: true }
content:
  - name: menu
    label: Navigeringsmeny
    type: file
    path: src/content/meny.json
    format: json
    fields:
      - name: main
        type: object
        list: true
        fields:
          - { name: link, label: Huvudval, component: menuLink, required: true}
          - { name: submenu, label: Undermeny, component: menuLink, list: true}
  - name: homepage
    label: Framsidan
    type: file
    path: src/content/framsidan.json
    format: json
    fields:
      - name: sections
        label: Sektioner
        type: object
        list: true
        fields:
          - { name: image, label: Bild, type: image }
          - { name: body, label: Text, type: rich-text, required: true }
          - name: link
            component: articleLink
  - name: faq
    label: FAQ
    type: file
    path: src/content/faq.json
    format: json
    fields:
      - name: questions
        label: Frågor
        type: object
        list: true
        fields:
          - { name: question, label: Fråga, type: string, required: true}
          - { name: answer, label: Svar, type: rich-text}
          - name: link
            component: articleLink
  - name: articles
    label: Artiklar
    type: collection
    path: src/content/articles
    filename: "{primary}.md"
    fields:
      - { name: title, label: Titel, type: string, required: true }
      - { name: order, label: Rang, type: number, required: true }
      - { name: image, label: Bild, type: image }
      - { name: body, label: Innehåll, type: rich-text }
  - name: lodges
    label: Loger
    type: collection
    path: src/content/lodges
    filename: "{primary}.md"
    fields:
      - { name: name, label: Namn, type: string, required: true }
      - { name: number, label: Nummer, type: number, required: true }
      - { name: city, label: Ort, type: string, required: true }
      - { name: streetAddress, label: Gatuadress, type: string, required: true }
      - { name: email, label: E-post, type: string, required: true }
      - {
          name: seal,
          label: Sigill,
          type: image,
          required: true,
          media: images,
        }
      - { name: meetingInfo, label: Mötesinfo, type: string }
      - name: schedule
        label: Arbetsordning
        type: object
        fields:
          - { name: date, label: Datum, type: date }
          - { name: work, label: Arbete, type: string }
        list: true
        required: true
      - { name: body, label: Beskrivning, type: rich-text, required: true }
